<a href="https://colab.research.google.com/github/dhruv572/Big_Data_Assignments/blob/main/LabEval_Mca1_202301014.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
# Multiply the following matrices and also find covariance between matrcies using numpy

import numpy as np

p = [[1,2],[2,3]]
q = [[4,5],[6,7]]

prod = np.matmul(p,q)
cov = np.cov(p,q)

print("Product of two matrices is : ",prod)
print("Covariance of two matrices is : ",cov)

Product of two matrices is :  [[16 19]
 [26 31]]
Covariance of two matrices is :  [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
